/*
 * TextDisplayer.java
 *
 * Created on 01 December 2004, 16:12
 */

package uk.ac.rdg.resc.jstyx.client.browser;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.BufferedReader;
import java.io.Reader;
import java.io.IOException;

import uk.ac.rdg.resc.jstyx.client.StyxFileInputStream;
import uk.ac.rdg.resc.jstyx.client.StyxFileInputStreamReader;
import uk.ac.rdg.resc.jstyx.StyxUtils;

/**
 * Displays the text from a file in a widget
 * @todo handle the window sizing properly
 * @author  jdb
 */
public class TextDisplayer extends javax.swing.JFrame
{
    
    /** Creates new form TextDisplayer */
    public TextDisplayer(String title)
    {
        super(title);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    /**
     * Reads all the data from the input stream and displays in the text area
     */
    public void displayData (InputStream is) throws IOException
    {
        Reader reader;
        if (is instanceof StyxFileInputStream)
        {
            reader = new StyxFileInputStreamReader((StyxFileInputStream)is);
        }
        else
        {
            // Used for reading local files
            reader = new InputStreamReader(is);
        }
        BufferedReader bufReader = new BufferedReader(reader);
        //int i;
        StringBuffer sBuf = new StringBuffer(this.jTextPane1.getText());
        String s;
        do
        {
            //i = bufReader.read();
            s = bufReader.readLine();
            if (s != null)
            {
                sBuf.append(s + StyxUtils.SYSTEM_NEWLINE);
            }
        } while (s != null);
        
        is.close();
        this.jTextPane1.setText(sBuf.toString());
        this.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
    
}
