/*
 * ParametersPanel.java
 *
 * Created on 18 May 2005, 11:02
 */

package uk.ac.rdg.resc.jstyx.gridservice.client;

/**
 *
 * @author  jdb
 */
public class ParametersPanel extends javax.swing.JPanel
{
    
    /** Creates new form ParametersPanel */
    public ParametersPanel()
    {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        
        setLayout(new java.awt.BorderLayout());
        
    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
